<?php 

/*

Contains the code for the advanced custom fields, only needs to be imported into the functions file if not in database. 

*/

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_59d28665bd69a',
	'title' => 'History',
	'fields' => array (
		array (
			'key' => 'field_5919ac48312cf',
			'label' => 'Presenting complaint',
			'name' => 'presenting_complaint',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'row_min' => '',
			'row_limit' => '',
			'layout' => 'row',
			'button_label' => 'Add Row',
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_5919f685246f6',
					'label' => 'Hide section',
					'name' => 'hidden',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_5919b890be246',
					'label' => 'Prompt',
					'name' => 'prompt',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5919f685246f6',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5919ac61312d0',
					'label' => 'Details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'tabs' => 'all',
					'delay' => 0,
				),
			),
		),
		array (
			'key' => 'field_5919b17f5742e',
			'label' => 'History of presenting complaint',
			'name' => 'history_of_presenting_complaint',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'row_min' => '',
			'row_limit' => '',
			'layout' => 'row',
			'button_label' => 'Add Row',
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_5919f6d8ee802',
					'label' => 'Hide section',
					'name' => 'hidden',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_5919b8a21480e',
					'label' => 'Prompt',
					'name' => 'prompt',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5919f6d8ee802',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5919b17f5742f',
					'label' => 'Details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'tabs' => 'all',
					'delay' => 0,
				),
			),
		),
		array (
			'key' => 'field_5919b1ba57432',
			'label' => 'Past medical history',
			'name' => 'past_medical_history',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'row_min' => '',
			'row_limit' => '',
			'layout' => 'row',
			'button_label' => 'Add Row',
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_5919f705ee803',
					'label' => 'Hide section',
					'name' => 'hidden',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_5919b8e20d85f',
					'label' => 'Prompt',
					'name' => 'prompt',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5919f705ee803',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5919b1ba57433',
					'label' => 'Details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'tabs' => 'all',
					'delay' => 0,
				),
			),
		),
		array (
			'key' => 'field_5919b1c157434',
			'label' => 'Family history',
			'name' => 'family_history',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'row_min' => '',
			'row_limit' => '',
			'layout' => 'row',
			'button_label' => 'Add Row',
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_5919f745ee804',
					'label' => 'Hide section',
					'name' => 'hidden',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_5919b8e90d860',
					'label' => 'Prompt',
					'name' => 'prompt',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5919f745ee804',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5919b1c157435',
					'label' => 'Details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'tabs' => 'all',
					'delay' => 0,
				),
			),
		),
		array (
			'key' => 'field_59d288b66a348',
			'label' => 'Social History',
			'name' => 'social_history',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_59d288b66a349',
					'label' => 'Hide section',
					'name' => 'hidden',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_59d288b66a34a',
					'label' => 'Prompt',
					'name' => 'prompt',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d288b66a349',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59d288b66a34b',
					'label' => 'Details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array (
			'key' => 'field_59d28ead685b0',
			'label' => 'Medication History',
			'name' => 'medication_history',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_59d28ead685b1',
					'label' => 'Hide section',
					'name' => 'hidden',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_59d28ead685b2',
					'label' => 'Prompt',
					'name' => 'prompt',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d28ead685b1',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59d28ead685b3',
					'label' => 'Details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array (
			'key' => 'field_59e3268d66ab1',
			'label' => 'Differential Diagnosis',
			'name' => 'differential_diagnosis_1',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_59e3268d66ab2',
					'label' => 'Hide section',
					'name' => 'hidden',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_59e3268d66ab3',
					'label' => 'Prompt',
					'name' => 'prompt',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59e3268d66ab2',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59e3268d66ab4',
					'label' => 'Details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'article',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59d28ee0d7458',
	'title' => 'Neurology Examination',
	'fields' => array (
		array (
			'key' => 'field_59dbd724a28f8',
			'label' => 'Hide Examination',
			'name' => 'hide_examination',
			'type' => 'true_false',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59dbd748a28f9',
			'label' => 'Prompt',
			'name' => 'examination_prompt',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59d2bdbfd8572',
			'label' => 'Examination Free Text',
			'name' => 'examination_free_text',
			'type' => 'wysiwyg',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array (
			'key' => 'field_59d2bb921ca40',
			'label' => 'Toggle UL',
			'name' => 'toggle_ul',
			'type' => 'true_false',
			'value' => NULL,
			'instructions' => 'Toggle',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Click to Enter Upper Limb Examination',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59d29201b7da0',
			'label' => 'Shoulder Ab',
			'name' => 'shoulder_ab',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d2bb921ca40',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59d29232b7da1',
					'label' => 'Shoulder Abduction Right',
					'name' => 'shoulder_abduction_r',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d29f7faab28',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d293cc2ab25',
					'label' => 'Shoulder Abduction Left',
					'name' => 'shoulder_abduction_l',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d29f7faab28',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d29f7faab28',
					'label' => 'ToggleShAb',
					'name' => 'toggle_shoulder_ab',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59d2a1ecc1765',
			'label' => 'Shoulder Ad',
			'name' => 'shoulder_ad',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d2bb921ca40',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59d2a1ecc1766',
					'label' => 'Shoulder Adduction Right',
					'name' => 'shoulder_adduction_r',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d2a1ecc1768',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d2a1ecc1767',
					'label' => 'Shoulder Adduction Left',
					'name' => 'shoulder_adduction_l',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d2a1ecc1768',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d2a1ecc1768',
					'label' => 'ToggleShAd',
					'name' => 'toggle_shoulder_ad',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59d2a30394c63',
			'label' => 'Elbow Fl',
			'name' => 'elbow_fl',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d2bb921ca40',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59d2a30394c64',
					'label' => 'Elbow Flexion Right',
					'name' => 'elbow_flexion_r',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d2a30394c66',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d2a30394c65',
					'label' => 'Elbow Flexion Left',
					'name' => 'elbow_flexion_l',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d2a30394c66',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d2a30394c66',
					'label' => 'ToggleElbFl',
					'name' => 'toggle_elbow_fl',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59d2a3b8b93b5',
			'label' => 'Elbow Ex',
			'name' => 'elbow_ex',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d2bb921ca40',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59d2a3b8b93b6',
					'label' => 'Elbow Extension Right',
					'name' => 'elbow_extension_r',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d2a3b8b93b8',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d2a3b8b93b7',
					'label' => 'Elbow Extension Left',
					'name' => 'elbow_extension_l',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d2a3b8b93b8',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d2a3b8b93b8',
					'label' => 'ToggleElbEx',
					'name' => 'toggle_elbow_ex',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59d2a596d149f',
			'label' => 'Wrist Fl',
			'name' => 'wrist_fl',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d2bb921ca40',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59d2a596d14a0',
					'label' => 'Wrist Flexion Right',
					'name' => 'wrist_flexion_r',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d2a596d14a2',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d2a596d14a1',
					'label' => 'Wrist Flexion Left',
					'name' => 'wrist_flexion_l',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d2a596d14a2',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d2a596d14a2',
					'label' => 'ToggleWristFl',
					'name' => 'toggle_wrist_fl',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59d2a73d56277',
			'label' => 'Wrist Ex',
			'name' => 'wrist_ex',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d2bb921ca40',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59d2a73d56278',
					'label' => 'Wrist Extension Right',
					'name' => 'wrist_extension_r',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d2a73d5627a',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d2a73d56279',
					'label' => 'Wrist Extension Left',
					'name' => 'wrist_extension_l',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d2a73d5627a',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d2a73d5627a',
					'label' => 'ToggleWristEx',
					'name' => 'toggle_wrist_ex',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59d3d35dcb4ce',
			'label' => 'Toggle LL',
			'name' => 'toggle_ll',
			'type' => 'true_false',
			'value' => NULL,
			'instructions' => 'Toggle',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Click to Enter Lower Limb Examination',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59d3d38ecb4cf',
			'label' => 'Hip Fl',
			'name' => 'hip_fl',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d3d35dcb4ce',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59d3d38ecb4d0',
					'label' => 'Hip Flextion Right',
					'name' => 'hip_flexion_r',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d3d38ecb4d2',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d3d38ecb4d1',
					'label' => 'Hip Flextion Left',
					'name' => 'hip_flexion_l',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d3d38ecb4d2',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d3d38ecb4d2',
					'label' => 'ToggleHipFl',
					'name' => 'toggle_hip_fl',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59d3d42f53b7b',
			'label' => 'Hip Ex',
			'name' => 'hip_ex',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d3d35dcb4ce',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59d3d42f53b7c',
					'label' => 'Hip Extension Right',
					'name' => 'hip_extension_r',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d3d42f53b7e',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d3d42f53b7d',
					'label' => 'Hip Extension Left',
					'name' => 'hip_extension_l',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d3d42f53b7e',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d3d42f53b7e',
					'label' => 'ToggleHipEx',
					'name' => 'toggle_hip_ex',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59d3d8953c7e9',
			'label' => 'Knee Fl',
			'name' => 'knee_fl',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d3d35dcb4ce',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59d3d8953c7ea',
					'label' => 'Knee Flextion Right',
					'name' => 'knee_flexion_r',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d3d8953c7ec',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d3d8953c7eb',
					'label' => 'Knee Flextion Left',
					'name' => 'knee_flexion_l',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d3d8953c7ec',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d3d8953c7ec',
					'label' => 'ToggleKneeFl',
					'name' => 'toggle_knee_fl',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59d3d8f41f736',
			'label' => 'Knee Ex',
			'name' => 'knee_ex',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d3d35dcb4ce',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59d3d8f41f737',
					'label' => 'Knee Extension Right',
					'name' => 'knee_extension_r',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d3d8f41f739',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d3d8f41f738',
					'label' => 'Knee Extension Left',
					'name' => 'knee_extension_l',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59d3d8f41f739',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59d3d8f41f739',
					'label' => 'ToggleKneeEx',
					'name' => 'toggle_knee_ex',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59db8fa17d42a',
			'label' => 'Ankle DFl',
			'name' => 'ankle_dfl',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d3d35dcb4ce',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59db8fa17d42b',
					'label' => 'Ankle Dorsiflexion Right',
					'name' => 'ankle_dorsiflexion_r',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59db8fa17d42d',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59db8fa17d42c',
					'label' => 'Ankle Dorsiflextion Left',
					'name' => 'ankle_dorsiflexion_l',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59db8fa17d42d',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59db8fa17d42d',
					'label' => 'ToggleAnkeDFl',
					'name' => 'toggle_ankle_dfl',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59db90752c5e7',
			'label' => 'Ankle PFl',
			'name' => 'ankle_pfl',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d3d35dcb4ce',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59db90752c5e8',
					'label' => 'Ankle Plantarflexion Right',
					'name' => 'ankle_plantarflexion_r',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59db90752c5ea',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59db90752c5e9',
					'label' => 'Ankle Plantarflexion Left',
					'name' => 'ankle_plantarflexion_l',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59db90752c5ea',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 5,
					'placeholder' => '',
					'prepend' => '',
					'append' => '/5',
					'min' => 0,
					'max' => 5,
					'step' => 1,
				),
				array (
					'key' => 'field_59db90752c5ea',
					'label' => 'ToggleAnkeDFl',
					'name' => 'toggle_ankle_pfl',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59d672d444145',
			'label' => 'Toggle Reflexes',
			'name' => 'toggle_reflexes',
			'type' => 'true_false',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59da877ba8c0c',
			'label' => 'Reflexes Free Text',
			'name' => 'reflexes_free_text',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d672d444145',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59dbc0d90a1a8',
			'label' => 'Reflexes Biceps',
			'name' => 'reflexes_biceps',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d672d444145',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59dbc0fd0a1a9',
					'label' => 'Biceps Right',
					'name' => 'biceps_r',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbc14e0a1ab',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '+',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbc12e0a1aa',
					'label' => 'Biceps Left',
					'name' => 'biceps_l',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbc14e0a1ab',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '+',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbc14e0a1ab',
					'label' => 'Toggle Biceps',
					'name' => 'toggle_biceps',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59dbc1dcf1c9a',
			'label' => 'Reflexes Triceps',
			'name' => 'reflexes_triceps',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d672d444145',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59dbc1dcf1c9b',
					'label' => 'Triceps Right',
					'name' => 'triceps_r',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbc1dcf1c9d',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '+',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbc1dcf1c9c',
					'label' => 'Triceps Left',
					'name' => 'triceps_l',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbc1dcf1c9d',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '+',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbc1dcf1c9d',
					'label' => 'Toggle Triceps',
					'name' => 'toggle_triceps',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59dbc2c83282d',
			'label' => 'Reflexes Brachioradialis',
			'name' => 'reflexes_brachioradialis',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d672d444145',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59dbc2c83282e',
					'label' => 'Brachioradialis Right',
					'name' => 'brachioradialis_r',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbc2c832830',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '+',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbc2c83282f',
					'label' => 'Brachioradialis Left',
					'name' => 'brachioradialis_l',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbc2c832830',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '+',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbc2c832830',
					'label' => 'Toggle Brachioradialis',
					'name' => 'toggle_brachioradialis',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59dbc6b9ed6cf',
			'label' => 'Reflexes Patella',
			'name' => 'reflexes_patella',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d672d444145',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59dbc6baed6d0',
					'label' => 'Patella Right',
					'name' => 'patella_r',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbc6baed6d2',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '+',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbc6baed6d1',
					'label' => 'Patella Left',
					'name' => 'patella_l',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbc6baed6d2',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '+',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbc6baed6d2',
					'label' => 'Toggle Patella',
					'name' => 'toggle_patella',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59dbc7ef0d2fe',
			'label' => 'Reflexes Ankle',
			'name' => 'reflexes_ankle',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d672d444145',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59dbc7ef0d2ff',
					'label' => 'Ankle Right',
					'name' => 'ankle_r',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbc7ef0d301',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '+',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbc7ef0d300',
					'label' => 'Ankle Left',
					'name' => 'ankle_l',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbc7ef0d301',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '+',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbc7ef0d301',
					'label' => 'Toggle Ankle',
					'name' => 'toggle_ankle',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59dbc839141e1',
			'label' => 'Reflexes Plantar',
			'name' => 'reflexes_plantar',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d672d444145',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59dbc839141e2',
					'label' => 'Plantar Right',
					'name' => 'plantar_r',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbc839141e4',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Down',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbc839141e3',
					'label' => 'Plantar Left',
					'name' => 'plantar_l',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbc839141e4',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Down',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbc839141e4',
					'label' => 'Toggle Plantar',
					'name' => 'toggle_plantar',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59dbf63e08caf',
			'label' => 'Clonus',
			'name' => 'clonus',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59d672d444145',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59dbf63e08cb0',
					'label' => 'Clonus Right',
					'name' => 'clonus_r',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbf63e08cb2',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'None',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbf63e08cb1',
					'label' => 'Clonus Left',
					'name' => 'clonus_l',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dbf63e08cb2',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'None',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dbf63e08cb2',
					'label' => 'Toggle Clonus',
					'name' => 'toggle_clonus',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array (
			'key' => 'field_59ddd3b2586f7',
			'label' => 'Media',
			'name' => 'media',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_59de25835272f',
					'label' => 'Media Location',
					'name' => 'media_location',
					'type' => 'select',
					'value' => NULL,
					'instructions' => 'Position of media content within exam',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'top' => 'Top',
						'ep' => 'Exam Prompt',
						'eft' => 'Exam Free Text',
						'cne' => 'Cranial Nerve',
						'ule' => 'Upper Limb Exam',
						'lle' => 'Lower Limb Examination',
						'bottom' => 'Bottom',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_59ddd40c586f8',
					'label' => 'Media Content',
					'name' => 'media_content',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'article',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59dfe1adb6129',
	'title' => 'Investigations',
	'fields' => array (
		array (
			'key' => 'field_59e29febf936a',
			'label' => 'Differential Diagnosis',
			'name' => 'differential_diagnosis_2',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_59e29febf936b',
					'label' => 'Hide section',
					'name' => 'hidden',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_59e29febf936c',
					'label' => 'Prompt',
					'name' => 'prompt',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59e29febf936b',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59e29febf936d',
					'label' => 'Details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array (
			'key' => 'field_59dfe1adbce41',
			'label' => 'Blood Tests',
			'name' => 'blood_tests',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_59dfe1adbf7bd',
					'label' => 'Hide section',
					'name' => 'hidden',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_59dfe1adbf7d7',
					'label' => 'Prompt',
					'name' => 'prompt',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dfe1adbf7bd',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dfe1adbf7e7',
					'label' => 'Details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'tabs' => 'all',
					'delay' => 0,
				),
			),
		),
		array (
			'key' => 'field_59dfe29a03b5d',
			'label' => 'Imaging Tests',
			'name' => 'imaging_tests',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_59dfe29a03b5e',
					'label' => 'Hide section',
					'name' => 'hidden',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_59dfe29a03b5f',
					'label' => 'Prompt',
					'name' => 'prompt',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dfe29a03b5e',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dfe29a03b60',
					'label' => 'Details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array (
			'key' => 'field_59dfe2d140a01',
			'label' => 'Special Tests',
			'name' => 'special_tests',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_59dfe2d140a02',
					'label' => 'Hide section',
					'name' => 'hidden',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_59dfe2d140a03',
					'label' => 'Prompt',
					'name' => 'prompt',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59dfe2d140a02',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59dfe2d140a04',
					'label' => 'Details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'article',
			),
		),
	),
	'menu_order' => 3,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59de86e8d6e85',
	'title' => 'Discussion',
	'fields' => array (
		array (
			'key' => 'field_59de86e8dfda1',
			'label' => 'Differential Diagnosis',
			'name' => 'differential_diagnosis_3',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_59de86e8e2881',
					'label' => 'Hide section',
					'name' => 'hidden',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_59de86e8e28a3',
					'label' => 'Prompt',
					'name' => 'prompt',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59de86e8e2881',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59de86e8e28f7',
					'label' => 'Details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'tabs' => 'all',
					'delay' => 0,
				),
			),
		),
		array (
			'key' => 'field_59e210d046fef',
			'label' => 'Discussion',
			'name' => 'discussion',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_59e210d046ff0',
					'label' => 'Hide section',
					'name' => 'hidden',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_59e210d046ff1',
					'label' => 'Prompt',
					'name' => 'prompt',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59e210d046ff0',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59e210d046ff2',
					'label' => 'Details',
					'name' => 'details',
					'type' => 'wysiwyg',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'article',
			),
		),
	),
	'menu_order' => 4,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59e9071c53ddf',
	'title' => 'References',
	'fields' => array (
		array (
			'key' => 'field_59e90743151e3',
			'label' => 'References',
			'name' => 'references',
			'type' => 'textarea',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'article',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;


 ?>